TILE_SIZE = 16
VIEW_WIDTH = 13
VIEW_HEIGHT = 13

TILE_WIDTH = 64
TILE_HEIGHT = 64

MINIMAP_TILE_SIZE = 1

GAME_WIDTH = TILE_SIZE*(VIEW_WIDTH+2) + MINIMAP_TILE_SIZE * (TILE_WIDTH + 20)
GAME_HEIGHT = TILE_SIZE*(VIEW_HEIGHT+2)

GAME_TITLE = "ダンジョン伝説"
